In [1]:
import pandas as pd
import numpy as np

In [53]:
odds_data=pd.read_pickle('../Odds_Data.pkl')
meta_data=pd.read_pickle('../meta_data.pkl')
matchup_data=pd.read_pickle('../Scrapped Data/Game_Data_Full.pkl')
batting_annuals=pd.read_pickle('../Scrapped Data/team_batting_splits.pkl')
batting_games=pd.read_pickle('../Scrapped Data/team_batting_gamelogs.pkl')
pitcher_annuals=pd.read_pickle('../Scrapped Data/pitcher_splits.pkl')
pitcher_games=pd.read_pickle('../Scrapped Data/pitcher_games.pkl')

In [66]:
batting_games['#']=batting_games['#'].astype(int)

In [67]:
batting_games['Runs_YTD']=batting_games.groupby(['year','Team'])['Runs'].cumsum()
batting_games.Runs_YTD=batting_games.apply(lambda r:r.Runs_YTD-r.Runs,axis=1)
batting_games['Avg_Runs_YTD']=batting_games.Runs_YTD/batting_games['#']
batting_games

,#,Date,HA,Opp,Outcome,PA,AB,Runs,Hits,2B,...,OPS,Left_on_Base,Players_Used,Starter_LR,Starter_GScore,link,year,Team,Runs_YTD,Avg_Runs_YTD
index,,,,,,,,,,,,,,,,,,,,,
ARI_2019_1,1,2019-03-28,@,LAD,"L,5-12",35,33,5,9,4,...,.833,3,11,L,H.Ryu(68),/boxes/LAN/LAN201903280.shtml,2019,ARI,0,0.000000
ARI_2019_2,2,2019-03-29,@,LAD,"W,5-4",56,50,5,10,3,...,.696,12,18,R,R.Stripling(66),/boxes/LAN/LAN201903290.shtml,2019,ARI,5,2.500000
ARI_2019_3,3,2019-03-30,@,LAD,"L,5-18",35,32,5,7,0,...,.747,3,13,R,K.Maeda(56),/boxes/LAN/LAN201903300.shtml,2019,ARI,10,3.333333
ARI_2019_4,4,2019-03-31,@,LAD,"L,7-8",40,39,7,13,2,...,.776,6,15,R,W.Buehler(28),/boxes/LAN/LAN201903310.shtml,2019,ARI,15,3.750000
ARI_2019_5,5,2019-04-01,@,SDP,"W,10-3",45,40,10,15,5,...,.822,8,11,L,M.Strahm(21),/boxes/SDN/SDN201904010.shtml,2019,ARI,22,4.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSN_2015_158,158,2015-09-30,@,ATL,"L,0-2",34,31,0,6,2,...,.730,7,11,R,W.Perez(60),/boxes/ATL/ATL201509300.shtml,2015,WSN,695,4.398734
WSN_2015_159,159,2015-10-01,@,ATL,"W,3-0",34,33,3,6,0,...,.728,4,15,R,R.Weber(73),/boxes/ATL/ATL201510010.shtml,2015,WSN,695,4.371069
WSN_2015_160,160,2015-10-03,@,NYM,"W,3-1",34,29,3,4,1,...,.728,4,15,R,N.Syndergaard(78),/boxes/NYN/NYN201510031.shtml,2015,WSN,698,4.362500
WSN_2015_161,161,2015-10-03,@,NYM,"W,2-0",34,32,2,5,0,...,.726,5,10,R,M.Harvey(73),/boxes/NYN/NYN201510032.shtml,2015,WSN,701,4.354037
WSN_2015_162,162,2015-10-04,@,NYM,"L,0-1",31,29,0,2,1,...,.724,4,12,R,J.deGrom(67),/boxes/NYN/NYN201510040.shtml,2015,WSN,703,4.339506

index
ARI_2019_1        0
ARI_2019_2        5
ARI_2019_3       10
ARI_2019_4       15
ARI_2019_5       22
               ...
WSN_2015_158    695
WSN_2015_159    695
WSN_2015_160    698
WSN_2015_161    701
WSN_2015_162    703
Length: 24294, dtype: int64

In [52]:
X=X.dropna()

In [76]:
def annual_bat_stat(team,year,statistic):
    return float(batting_annuals.loc[team+str(year)][statistic])
def annual_pitch_stat(pitcher,year,statistic):

In [141]:
def STD_bat_stat(team,date,statistic):
    year=date.year
    qualifier=((batting_games.team==team) & (batting_games.Date < date) & (batting_games.year==date.year))
    observations=batting_games[qualifier][statistic]
    return observations

In [65]:
stats=list(batting_annuals.columns)
stats.remove('Tm')
stats.remove('G')
stats.remove('Yr')

In [143]:
d=batting_games.iloc[200].Date
team='BOS'
STD_bat_stat(team,d,'OPS')

2669    .668
2670    .794
2671    .712
2672    .752
2673    .689
        ...
2804    .826
2805    .826
2806    .825
2807    .825
2808    .823
Name: OPS, Length: 140, dtype: object

In [138]:
observations

,index,#,Date,HA,Opp,Outcome,PA,AB,Runs,Hits,...,OBP,Slugging,OPS,Left_on_Base,Players_Used,Starter_LR,Starter_GScore,link,year,team
2609,BOS_2020_1,1,2020-07-24,,BAL,"W,13-2",47,40,13,17,...,.511,.625,1.136,10,12,L,T.Milone(37),/boxes/BOS/BOS202007240.shtml,2020,BOS
2610,BOS_2020_2,2,2020-07-25,,BAL,"L,2-7",39,37,2,9,...,.407,.481,.887,10,10,R,A.Cobb(62),/boxes/BOS/BOS202007250.shtml,2020,BOS
2611,BOS_2020_3,3,2020-07-26,,BAL,"L,4-7",34,34,4,7,...,.350,.459,.809,3,10,L,W.LeBlanc(49),/boxes/BOS/BOS202007260.shtml,2020,BOS

In [77]:
for s in stats:
    X[s]=X.apply(lambda r:(annual_bat_stat(r['away'],r['year_x'],s)+annual_bat_stat(r['home'],r['year_x'],s))/2,axis=1)

<ipython-input-77-86794d162f6f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[s]=X.apply(lambda r:(annual_bat_stat(r['away'],r['year_x'],s)+annual_bat_stat(r['home'],r['year_x'],s))/2,axis=1)

In [111]:
STD_bat_stat('BOS',batting_games.loc[3].Date,'Slugging')

<ipython-input-110-f7608bb2c4bb>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  observations=batting_annuals[qualifier][statistic]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [121]:
batting_games=batting_games.reset_index()
batting_games

,index,#,Date,HA,Opp,Outcome,PA,AB,Runs,Hits,...,AVG,OBP,Slugging,OPS,Left_on_Base,Players_Used,Starter_LR,Starter_GScore,link,year
0,ARI_2020_1,1,2020-07-24,@,SDP,"L,2-7",33,32,2,7,...,.219,.242,.344,.586,4,11,R,C.Paddack(67),/boxes/SDN/SDN202007240.shtml,2020
1,ARI_2020_2,2,2020-07-25,@,SDP,"L,1-5",33,32,1,5,...,.188,.212,.297,.509,5,11,R,D.Lamet(60),/boxes/SDN/SDN202007250.shtml,2020
2,ARI_2020_3,3,2020-07-26,@,SDP,"W,4-3",39,31,4,7,...,.200,.267,.284,.551,8,11,R,G.Richards(68),/boxes/SDN/SDN202007260.shtml,2020
3,ARI_2020_4,4,2020-07-27,@,SDP,"L,2-6",37,33,2,6,...,.195,.268,.266,.533,8,11,L,J.Lucchesi(44),/boxes/SDN/SDN202007270.shtml,2020
4,ARI_2020_5,5,2020-07-28,@,TEX,"W,4-1",40,34,4,8,...,.204,.286,.272,.557,9,9,R,K.Gibson(52),/boxes/TEX/TEX202007280.shtml,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26085,WSN_2015_158,158,2015-09-30,@,ATL,"L,0-2",34,31,0,6,...,.254,.324,.406,.730,7,11,R,W.Perez(60),/boxes/ATL/ATL201509300.shtml,2015
26086,WSN_2015_159,159,2015-10-01,@,ATL,"W,3-0",34,33,3,6,...,.253,.323,.405,.728,4,15,R,R.Weber(73),/boxes/ATL/ATL201510010.shtml,2015
26087,WSN_2015_160,160,2015-10-03,@,NYM,"W,3-1",34,29,3,4,...,.253,.323,.405,.728,4,15,R,N.Syndergaard(78),/boxes/NYN/NYN201510031.shtml,2015
26088,WSN_2015_161,161,2015-10-03,@,NYM,"W,2-0",34,32,2,5,...,.252,.322,.404,.726,5,10,R,M.Harvey(73),/boxes/NYN/NYN201510032.shtml,2015
26089,WSN_2015_162,162,2015-10-04,@,NYM,"L,0-1",31,29,0,2,...,.251,.321,.403,.724,4,12,R,J.deGrom(67),/boxes/NYN/NYN201510040.shtml,2015

In [122]:
batting_games['team']=batting_games['index'].apply(lambda s:s.split('_')[0])

In [107]:
batting_games.year

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
26085    2015
26086    2015
26087    2015
26088    2015
26089    2015
Name: year, Length: 26090, dtype: object