In [1]:
import pandas as pd
import numpy as np

In [3]:
def calc_YTD_Avg(df,stat):
    avg=df.groupby(df.Date.dt.year)[stat].cumsum().shift()/df.groupby(df.Date.dt.year)[stat].cumcount()
    avg.name='YTD_AVG_stat'
    return avg

In [8]:
pd.read_pickle('../Base DFs/team_batting_splits.pkl')

          #Bat  BatAge         PA         AB         R         H        2B  \
Tm  Yr
ARI 2014  52.0    27.6  37.586420  34.271605  3.796296  8.512346  1.598765
    2015  50.0    26.5  38.740741  34.870370  4.444444  9.222222  1.783951
    2016  50.0    26.7  38.641975  34.969136  4.641975  9.129630  1.759259
    2017  45.0    28.3  38.419753  34.104938  5.012346  8.672840  1.938272
    2018  49.0    29.2  38.006173  33.703704  4.277778  7.919753  1.598765
...        ...     ...        ...        ...       ...       ...       ...
WSN 2014  40.0    28.7  38.370370  34.209877  4.234568  8.660494  1.635802
    2015  44.0    28.4  37.759259  33.506173  4.339506  8.413580  1.635802
    2016  43.0    28.8  38.277778  33.888889  4.709877  8.660494  1.654321
    2017  49.0    29.2  38.358025  34.277778  5.055556  9.117284  1.919753
    2018  53.0    27.6  38.814815  34.055556  4.759259  8.654321  1.753086

                3B        HR       RBI  ...    SLG    OPS  OPS+         TB  \
Tm  Yr                                  ...
ARI 2014  0.290123  0.728395  3.537037  ...  0.376  0.678  88.0  12.876543
    2015  0.296296  0.950617  4.197531  ...  0.414  0.738  97.0  14.450617
    2016  0.345679  1.172840  4.376543  ...  0.432  0.752  93.0  15.098765
    2017  0.240741  1.358025  4.790123  ...  0.445  0.774  94.0  15.166667
    2018  0.308642  1.086420  4.061728  ...  0.397  0.707  86.0  13.395062
...            ...       ...       ...  ...    ...    ...   ...        ...
WSN 2014  0.166667  0.938272  3.919753  ...  0.393  0.714  96.0  13.444444
    2015  0.080247  1.092593  4.104938  ...  0.403  0.724  96.0  13.487654
    2016  0.179012  1.253086  4.537037  ...  0.426  0.751  96.0  14.432099
    2017  0.191358  1.327160  4.913580  ...  0.449  0.782  99.0  15.401235
    2018  0.154321  1.179012  4.549383  ...  0.419  0.753  98.0  14.253086

               GDP       HBP        SH        SF       IBB        LO
Tm  Yr
ARI 2014  0.709877  0.265432  0.345679  0.222222  0.191358  0.672840
    2015  0.827160  0.203704  0.283951  0.351852  0.246914  0.709877
    2016  0.722222  0.308642  0.265432  0.234568  0.265432  0.685185
    2017  0.654321  0.333333  0.240741  0.166667  0.271605  0.685185
    2018  0.679012  0.320988  0.234568  0.277778  0.222222  0.666667
...            ...       ...       ...       ...       ...       ...
WSN 2014  0.709877  0.345679  0.370370  0.253086  0.179012  0.067901
    2015  0.796296  0.271605  0.339506  0.314815  0.234568  0.685185
    2016  0.629630  0.395062  0.296296  0.388889  0.302469  0.679012
    2017  0.716049  0.191358  0.265432  0.277778  0.345679  0.679012
    2018  0.641975  0.364198  0.253086  0.246914  0.345679  0.728395

[150 rows x 26 columns]